### ISSUE TITLE
GlobalEnvironmentVariables.cs Need refresh

### ISSUE THREAD

**Issue by BrewertonSantos** [BramonGdop/PIM#1]
This method namespace is nothing current.

this class method "Set" need 3 arguments, is these: h1 (string), latitude (float), longitude (float).
Environment Variables in this project don't need remove method.

**Comment by lucasnaja** [comment]
The method "SetEnvironmentVariable" from "Environment" class accepts only strings, so i just added a condition to check whether the "value" argument is splittable.

The "Remove" method has been removed from the class.
